# Generated by Django 5.2.4 on 2025-07-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Forward', 'Forward'), ('Defender', 'Defender'), ('Midfielder', 'Midfield'), ('Coach', 'Coach'), ('Ass_Coach', 'Assistant Coach'), ('Manager', 'Manager'), ('Team_doctor', 'Team Doctor'), ('GK', 'Goal Keeper')], max_length=20),
        ),
    ]
