# Generated by Django 5.2.4 on 2025-07-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('sports_manager', 'Sports Manager'), ('general_user', 'General'), ('Treasurer', 'Treasurer')], max_length=20),
        ),
    ]
